import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import simpeg_abdiel.config;
import simpeg_abdiel.Db;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LAB RPL 1
 */
public class FormGaji extends javax.swing.JFrame {

    public String id_peg = "";
    public String nama_peg = "";
    public String gol_peg = "";
    public String jmlh_anak = "";
    public long gapok;
    public long tunj_anak;
    Connection con;
    Statement stm;
    String sql;
    
    
    public FormGaji() {
        try {
            con = config.configDB();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(FormGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        load_table();
        kosong();
        loadComboData();
        hitungGajiTotal();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iddivisi4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        iddivisi5 = new javax.swing.JLabel();
        gajipk = new javax.swing.JTextField();
        iddivisi = new javax.swing.JLabel();
        iddivisi1 = new javax.swing.JLabel();
        iddivisi2 = new javax.swing.JLabel();
        iddivisi3 = new javax.swing.JLabel();
        tunjanak = new javax.swing.JTextField();
        tunjkshtn = new javax.swing.JTextField();
        tambahbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableGaji = new javax.swing.JTable();
        iddivisi6 = new javax.swing.JLabel();
        gajitotal = new javax.swing.JTextField();
        iddivisi7 = new javax.swing.JLabel();
        combolpeg = new javax.swing.JComboBox<>();
        combolpeglo = new javax.swing.JComboBox<>();
        combolpeganak = new javax.swing.JComboBox<>();
        searchbtn = new javax.swing.JButton();
        searchidpeg = new javax.swing.JTextField();
        iddivisi8 = new javax.swing.JLabel();
        clearbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iddivisi4.setText("NAMA");

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        iddivisi5.setText("GAJI POKOK");

        gajipk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gajipkActionPerformed(evt);
            }
        });

        iddivisi.setText("ID PEGAWAI");

        iddivisi1.setText("JUMLAH ANAK");

        iddivisi2.setText("TUNJANGAN ANAK");

        iddivisi3.setText("TUNJANGAN KESEHATAN");

        tunjanak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunjanakActionPerformed(evt);
            }
        });

        tunjkshtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunjkshtnActionPerformed(evt);
            }
        });
        tunjkshtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tunjkshtnKeyReleased(evt);
            }
        });

        tambahbtn.setText("TAMBAH");
        tambahbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahbtnActionPerformed(evt);
            }
        });

        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        JTableGaji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTableGaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableGajiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableGaji);

        iddivisi6.setText("GOLONGAN");

        gajitotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gajitotalActionPerformed(evt);
            }
        });

        iddivisi7.setText("GAJI TOTAL");

        combolpeg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combolpeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combolpegActionPerformed(evt);
            }
        });

        combolpeglo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IIa", "IIb", "IIc", "IId", "IIIa", "IIIb", "IIIc", "IIId", "IVa", "IVb", "IVc", "IVd" }));
        combolpeglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combolpegloActionPerformed(evt);
            }
        });

        combolpeganak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combolpeganak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combolpeganakActionPerformed(evt);
            }
        });

        searchbtn.setText("SEARCH");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        searchidpeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchidpegActionPerformed(evt);
            }
        });
        searchidpeg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchidpegKeyReleased(evt);
            }
        });

        iddivisi8.setText("CARI ID PEGAWAI");

        clearbtn.setText("CLEAR");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambahbtn)
                        .addGap(18, 18, 18)
                        .addComponent(updatebtn)
                        .addGap(18, 18, 18)
                        .addComponent(btnhapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(keluar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(iddivisi)
                                .addComponent(iddivisi4)
                                .addComponent(iddivisi1)
                                .addComponent(iddivisi2)
                                .addComponent(iddivisi3)
                                .addComponent(iddivisi5)
                                .addComponent(iddivisi6)
                                .addComponent(iddivisi7)
                                .addComponent(iddivisi8))
                            .addGap(127, 127, 127)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(searchidpeg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(clearbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nama)
                                        .addComponent(gajitotal)
                                        .addComponent(gajipk)
                                        .addComponent(tunjkshtn)
                                        .addComponent(tunjanak)
                                        .addComponent(combolpeglo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(combolpeganak, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(combolpeg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchidpeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchbtn)
                        .addComponent(clearbtn))
                    .addComponent(iddivisi8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iddivisi)
                    .addComponent(combolpeg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iddivisi4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iddivisi6)
                    .addComponent(combolpeglo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gajipk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iddivisi5))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iddivisi1)
                    .addComponent(combolpeganak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tunjanak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iddivisi2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iddivisi3)
                    .addComponent(tunjkshtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gajitotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iddivisi7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahbtn)
                    .addComponent(updatebtn)
                    .addComponent(btnhapus)
                    .addComponent(keluar))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
        nama.requestFocus();
    }//GEN-LAST:event_namaActionPerformed

    private void gajipkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gajipkActionPerformed
        // TODO add your handling code here:
        gajipk.requestFocus();
        hitungGajiTotal();
    }//GEN-LAST:event_gajipkActionPerformed

    private void tunjanakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunjanakActionPerformed
        // TODO add your handling code here:
        hitungGajiTotal();
    }//GEN-LAST:event_tunjanakActionPerformed

    private void tunjkshtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunjkshtnActionPerformed
       hitungGajiTotal();
        
    }//GEN-LAST:event_tunjkshtnActionPerformed

    private void tambahbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahbtnActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO gajipegawai VALUES ('"+combolpeg.getSelectedItem()+"',"+ "'"+nama.getText()+"','"+gajipk.getText()+"','"+combolpeganak.getSelectedItem()+"','"+tunjanak.getText()+"','"+tunjkshtn.getText()+"', '"+gajitotal.getText()+"', '"+combolpeglo.getSelectedItem()+"')";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_tambahbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="UPDATE gajipegawai SET id_pegawai = '"+combolpeg.getSelectedItem()+"', "+ "nama = '"+nama.getText()+"', "+ "gaji_pokok = '"+gajipk.getText()+"', "+ "jumlah_anak = '"+combolpeganak.getSelectedItem()+"', "+ "tunj_anak = '"+tunjanak.getText()+"', "+ "tunj_kesehatan = '"+tunjkshtn.getText()+"',"+ "gaji_total = '"+gajitotal.getText()+"',"+ "golongan = '"+combolpeglo.getSelectedItem()+"' WHERE id_pegawai = '"+combolpeg.getSelectedItem()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_updatebtnActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="delete from gajipegawai where id_pegawai='"+combolpeg.getSelectedItem()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "berhasil di hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        new menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void gajitotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gajitotalActionPerformed

        hitungGajiTotal();
        
    }//GEN-LAST:event_gajitotalActionPerformed

    private void combolpegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combolpegActionPerformed
        
        if (combolpeg.getSelectedItem() != null){
            String idPegawai = combolpeg.getSelectedItem().toString();
            try{
                Statement statement = con.createStatement();
                String sql = "SELECT * FROM pegawai where id_pegawai='"+ idPegawai +"'";
                ResultSet result = statement.executeQuery(sql);
                
            if (result.next()){
                nama.setText(result.getString("nama"));
                combolpeglo.setSelectedItem(result.getString("golongan"));
                
            }
           
            } catch (SQLException ex){
                    java.util.logging.Logger.getLogger(FormGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
        }
    }//GEN-LAST:event_combolpegActionPerformed

    private void combolpegloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combolpegloActionPerformed
        
        gol_peg = combolpeglo.getSelectedItem().toString();
        if (gol_peg == "IIa"){
            gapok = 3200000;
        }    
        else if (gol_peg == "IIb"){
            gapok = 3400000;
        }
        else if (gol_peg == "IIc"){
            gapok = 3700000;
        }
        else if (gol_peg == "IId"){
            gapok = 3900000;
        }
        else if (gol_peg == "IIIa"){
            gapok = 4100000;
        }
        else if (gol_peg == "IIIb"){
            gapok = 4300000;
        }
        else if (gol_peg == "IIIc"){
            gapok = 4500000;
        }
        else if (gol_peg == "IIId"){
            gapok = 4600000;
        }
        else
            if (gol_peg == "IVa"){
            gapok = 4800000;
        }
        else
            if (gol_peg == "IVb"){
            gapok = 5000000;
        }
        else
            if (gol_peg == "IVc"){
            gapok = 5500000;
        }
        else
            if (gol_peg == "IVd"){
            gapok = 6000000;
        }
         gajipk.setText(String.valueOf(gapok));
         hitungGajiTotal();
    }//GEN-LAST:event_combolpegloActionPerformed

    private void combolpeganakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combolpeganakActionPerformed
       
        jmlh_anak = combolpeganak.getSelectedItem().toString();
        if (jmlh_anak == "1"){
            tunj_anak = 1200000;
        }    
        else if (jmlh_anak == "2"){
            tunj_anak = 1500000;
        }
        else if (jmlh_anak == "3"){
            tunj_anak = 1800000;
        }
        else if (jmlh_anak == "4"){
            tunj_anak = 2100000;
        }
        else if (jmlh_anak == "5"){
            tunj_anak = 2400000;
        }
        else if (jmlh_anak == "6"){
            tunj_anak = 2700000;
        }
        else if (jmlh_anak == "7"){
            tunj_anak = 3000000;
        }
        else if (jmlh_anak == "8"){
            tunj_anak = 3300000;
        }
        else if (jmlh_anak == "9"){
            tunj_anak = 3600000;
        }
         else if (jmlh_anak == "10"){
            tunj_anak = 4000000;
        }
        tunjanak.setText(String.valueOf(tunj_anak));
        hitungGajiTotal();
        
    }//GEN-LAST:event_combolpeganakActionPerformed

    private void JTableGajiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableGajiMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_JTableGajiMouseClicked

    private void tunjkshtnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tunjkshtnKeyReleased
      
         hitungGajiTotal();
         
    }//GEN-LAST:event_tunjkshtnKeyReleased

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        try{
            ResultSet rs =  Db.getData ("SELECT * FROM gajipegawai WHERE id_pegawai='"+searchidpeg.getText()+"'");

            if (rs.next()){
                //searchidpeg.setText(rs.getString("id_pegawai"));
                combolpeg.setSelectedItem(rs.getString("id_pegawai"));
                nama.setText(rs.getString("nama"));
                gajipk.setText(rs.getString("gaji_pokok"));
                combolpeganak.setSelectedItem(rs.getString("jumlah_anak"));
                tunjanak.setText(rs.getString("tunj_anak"));
                tunjkshtn.setText(rs.getString("tunj_kesehatan"));
                gajitotal.setText(rs.getString("gaji_total"));
                combolpeglo.setSelectedItem(rs.getString("golongan"));
            }
            else{
                JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
            }

        }
        catch (Exception e){
            e.printStackTrace();

        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void searchidpegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchidpegActionPerformed
       
        searchbtn.doClick();

    }//GEN-LAST:event_searchidpegActionPerformed

    private void searchidpegKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchidpegKeyReleased
        
        String key = searchidpeg.getText();
        System.out.println(key);

        if (key !=""){
            searchData(key);
        }
        else
        {
            load_table();
        }

    }//GEN-LAST:event_searchidpegKeyReleased

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed

        kosong();

    }//GEN-LAST:event_clearbtnActionPerformed

    private void loadComboData(){
        
        combolpeg.removeAllItems();
        try{
            Statement statement = con.createStatement();
            String sqlAll = "SELECT * FROM pegawai";
            ResultSet resultAll = statement.executeQuery(sqlAll);
            
            while (resultAll.next()) {
                combolpeg.addItem(resultAll.getString("id_pegawai"));
            }
            
            String sql ="SELECT * FROM pegawai WHERE id_pegawai='" + combolpeg.getSelectedItem().toString() + "';";
            ResultSet result = statement.executeQuery(sql);
            
            if (result.next()){
                combolpeglo.setSelectedItem(result.getString("golongan"));
            }
            
        } catch (SQLException ex){
        }
    }
    
    private void hitungGajiTotal() {
        String gajiPokok = gajipk.getText();
        String tunjanganAnak = tunjanak.getText();
        String tunjanganKesehatan = tunjkshtn.getText();
        
        
        
        if (gajiPokok.isEmpty()){
            gajiPokok = "0";
        }
        if (tunjanganAnak.isEmpty()){
            tunjanganAnak = "0";
        }
        if (tunjanganKesehatan.isEmpty()){
            tunjanganKesehatan = "0";
        }
        
        double gajiTotal = Double.parseDouble(gajiPokok)+Double.parseDouble(tunjanganAnak)+Double.parseDouble(tunjanganKesehatan);
        gajitotal.setText("" + gajiTotal);
    }
    
   
      
        
      
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormGaji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableGaji;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton clearbtn;
    private javax.swing.JComboBox<String> combolpeg;
    private javax.swing.JComboBox<String> combolpeganak;
    private javax.swing.JComboBox<String> combolpeglo;
    private javax.swing.JTextField gajipk;
    private javax.swing.JTextField gajitotal;
    private javax.swing.JLabel iddivisi;
    private javax.swing.JLabel iddivisi1;
    private javax.swing.JLabel iddivisi2;
    private javax.swing.JLabel iddivisi3;
    private javax.swing.JLabel iddivisi4;
    private javax.swing.JLabel iddivisi5;
    private javax.swing.JLabel iddivisi6;
    private javax.swing.JLabel iddivisi7;
    private javax.swing.JLabel iddivisi8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField nama;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField searchidpeg;
    private javax.swing.JButton tambahbtn;
    private javax.swing.JTextField tunjanak;
    private javax.swing.JTextField tunjkshtn;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables

    private void load_table() {
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID PEGAWAI");
        model.addColumn("NAMA");
        model.addColumn("GAJI POKOK");
        model.addColumn("JUMLAH ANAK");
        model.addColumn("TUNJANGAN ANAK");
        model.addColumn("TUNJANGAN KESEHATAN");
        model.addColumn("GAJI TOTAL");
        model.addColumn("GOLONGAN");
        
        try{
            String sql = "select *from gajipegawai";
            java.sql.Connection conn= config.configDB();
            
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
               model.addRow(new 
                Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8)});
            }
            JTableGaji.setModel(model);
        }catch (SQLException e){
            
        }
    }

private void searchData(String keyID){
        try{
            
            Object [] listkolom = {"ID", "NAMA", "GAJI POKOK", "JUMLAH ANAK", "TUNJANGAN ANAK", "TUNJANGAN KESEHATAN", "GAJI TOTAL", "GOLONGAN"};
            DefaultTableModel dtm = new DefaultTableModel(null, listkolom);
             JTableGaji.setModel(dtm);
             Connection conn = (Connection)config.configDB();
             dtm.getDataVector().removeAllElements();
             ResultSet resu = conn.createStatement().executeQuery("SELECT * FROM gajipegawai WHERE id_pegawai LIKE '"+keyID+"%'");
             while(resu.next()){
                 Object[] data = {
                     resu.getString("id_pegawai"),
                     resu.getString("nama"),
                     resu.getString("gaji_pokok"),
                     resu.getString("jumlah_anak"),
                     resu.getString("tunj_anak"),
                     resu.getString("tunj_kesehatan"),
                     resu.getString("gaji_total"),
                     resu.getString("golongan")
                     
                 };
                 dtm.addRow(data);
             }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void kosong() {
        
        searchidpeg.setText(null);
        combolpeg.getSelectedItem();
        nama.setText(null);
        gajipk.setText(null);
        combolpeganak.getSelectedItem();
        tunjanak.setText(null);
        tunjkshtn.setText(null);
        gajitotal.setText(null);
        
    }

}

