import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import simpeg_abdiel.config;
import simpeg_abdiel.Db;

public class FormPegawai extends javax.swing.JFrame {

    public FormPegawai() {
        initComponents();
        load_table();
        kosong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtidjabatan = new javax.swing.JTextField();
        iddivisi = new javax.swing.JLabel();
        iddivisi1 = new javax.swing.JLabel();
        iddivisi2 = new javax.swing.JLabel();
        iddivisi3 = new javax.swing.JLabel();
        txtidpegawai = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtusia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablePegawai = new javax.swing.JTable();
        tambahbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        iddivisi4 = new javax.swing.JLabel();
        txtiddivisi = new javax.swing.JTextField();
        iddivisi5 = new javax.swing.JLabel();
        txtijabatan = new javax.swing.JTextField();
        iddivisi6 = new javax.swing.JLabel();
        combolpeglo = new javax.swing.JComboBox<>();
        searchbtn = new javax.swing.JButton();
        keluar1 = new javax.swing.JButton();

        txtidjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidjabatanActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iddivisi.setText("ID PEGAWAI");

        iddivisi1.setText("NAMA");

        iddivisi2.setText("ALAMAT");

        iddivisi3.setText("USIA");

        txtidpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpegawaiActionPerformed(evt);
            }
        });
        txtidpegawai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidpegawaiKeyReleased(evt);
            }
        });

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatActionPerformed(evt);
            }
        });

        txtusia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusiaActionPerformed(evt);
            }
        });

        JTablePegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTablePegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTablePegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTablePegawai);

        tambahbtn.setText("TAMBAH");
        tambahbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahbtnActionPerformed(evt);
            }
        });

        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        iddivisi4.setText("ID DIVISI");

        txtiddivisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtiddivisiActionPerformed(evt);
            }
        });

        iddivisi5.setText("ID JABATAN ");

        txtijabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtijabatanActionPerformed(evt);
            }
        });

        iddivisi6.setText("GOLONGAN");

        combolpeglo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IIa", "IIb", "IIc", "IId", "IIIa", "IIIb", "IIIc", "IIId", "IVa", "IVb", "IVc", "IVd" }));
        combolpeglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combolpegloActionPerformed(evt);
            }
        });

        searchbtn.setText("SEARCH");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        keluar1.setText("CLEAR");
        keluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iddivisi6)
                                .addGap(371, 371, 371))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iddivisi)
                                    .addComponent(iddivisi1)
                                    .addComponent(iddivisi2)
                                    .addComponent(iddivisi3)
                                    .addComponent(iddivisi4)
                                    .addComponent(iddivisi5))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtijabatan, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                    .addComponent(txtiddivisi, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                    .addComponent(txtusia, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                    .addComponent(txtalamat, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                    .addComponent(txtidpegawai, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                    .addComponent(txtnama, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                    .addComponent(combolpeglo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(searchbtn)
                        .addGap(18, 18, 18)
                        .addComponent(keluar1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tambahbtn)
                                .addGap(18, 18, 18)
                                .addComponent(updatebtn)
                                .addGap(18, 18, 18)
                                .addComponent(btnhapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(keluar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iddivisi)
                    .addComponent(searchbtn)
                    .addComponent(keluar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtiddivisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iddivisi4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtijabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iddivisi5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iddivisi6)
                    .addComponent(combolpeglo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iddivisi1)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iddivisi2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iddivisi3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahbtn)
                    .addComponent(updatebtn)
                    .addComponent(btnhapus)
                    .addComponent(keluar))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidjabatanActionPerformed
        // TODO add your handling code here:
        txtidjabatan.requestFocus();
    }//GEN-LAST:event_txtidjabatanActionPerformed

    private void txtidpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpegawaiActionPerformed
        // TODO add your handling code here:
        txtidjabatan.requestFocus();
        searchbtn.doClick();
    
         
    }//GEN-LAST:event_txtidpegawaiActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatActionPerformed

    private void txtusiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusiaActionPerformed

    private void tambahbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahbtnActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO pegawai VALUES ('"+txtidpegawai.getText()+"',"+ "'"+txtiddivisi.getText()+"','"+txtijabatan.getText()+"','"+txtnama.getText()+"','"+combolpeglo.getSelectedItem()+"','"+txtalamat.getText()+"','"+txtusia.getText()+"')";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());          
        }
        load_table();
        kosong();
    }//GEN-LAST:event_tambahbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="UPDATE pegawai SET id_divisi = '"+txtiddivisi.getText()+"', "+ "id_jabatan = '"+txtijabatan.getText()+"', "+ "nama = '"+txtnama.getText()+"',"+ "golongan = '"+combolpeglo.getSelectedItem()+"', "+ "alamat = '"+txtalamat.getText()+"', "+ "usia = '"+txtusia.getText()+"' WHERE id_pegawai = '"+txtidpegawai.getText()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_updatebtnActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="delete from pegawai where id_pegawai='"+txtidpegawai.getText()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "berhasil di hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        
        new menu().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_keluarActionPerformed

    private void txtiddivisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtiddivisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtiddivisiActionPerformed

    private void txtijabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtijabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtijabatanActionPerformed

    private void JTablePegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTablePegawaiMouseClicked
        // TODO add your handling code here:
         int baris = JTablePegawai.rowAtPoint(evt.getPoint());
        String id_pegawai =JTablePegawai.getValueAt(baris, 0).toString();
        txtidpegawai.setText(id_pegawai);      
        String id_divisi =JTablePegawai.getValueAt(baris, 1).toString();
        txtiddivisi.setText(id_divisi);
        String id_jabatan =JTablePegawai.getValueAt(baris, 2).toString();
        txtijabatan.setText(id_jabatan);   
        String nama =JTablePegawai.getValueAt(baris, 3).toString();
        txtnama.setText(nama);  
        String golong =JTablePegawai.getValueAt(baris, 4).toString();
        combolpeglo.setSelectedItem(golong);              
        String alamat =JTablePegawai.getValueAt(baris, 5).toString();
        txtalamat.setText(alamat);
        String usia =JTablePegawai.getValueAt(baris, 6).toString();
        txtusia.setText(usia);
    }//GEN-LAST:event_JTablePegawaiMouseClicked

    private void txtidpegawaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidpegawaiKeyReleased
        
         String key = txtidpegawai.getText();
        System.out.println(key);
        
        if (key !=""){
            searchData(key);
        }
        else
        {
            load_table();
        }
    }//GEN-LAST:event_txtidpegawaiKeyReleased

    private void combolpegloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combolpegloActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_combolpegloActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        try{
            ResultSet rs =  Db.getData ("SELECT * FROM pegawai WHERE id_pegawai='"+txtidpegawai.getText()+"'");

            if (rs.next()){
                txtidpegawai.setText(rs.getString("id_pegawai"));
                txtiddivisi.setText(rs.getString("id_divisi"));
                txtijabatan.setText(rs.getString("id_jabatan"));
                txtnama.setText(rs.getString("nama"));
                combolpeglo.setSelectedItem(rs.getString("golongan"));
                txtalamat.setText(rs.getString("alamat"));
                txtusia.setText(rs.getString("usia"));
            }
            else{
                JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
            }

        }
        catch (Exception e){
            e.printStackTrace();

        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void keluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluar1ActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_keluar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTablePegawai;
    private javax.swing.JButton btnhapus;
    private javax.swing.JComboBox<String> combolpeglo;
    private javax.swing.JLabel iddivisi;
    private javax.swing.JLabel iddivisi1;
    private javax.swing.JLabel iddivisi2;
    private javax.swing.JLabel iddivisi3;
    private javax.swing.JLabel iddivisi4;
    private javax.swing.JLabel iddivisi5;
    private javax.swing.JLabel iddivisi6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton keluar1;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton tambahbtn;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtiddivisi;
    private javax.swing.JTextField txtidjabatan;
    private javax.swing.JTextField txtidpegawai;
    private javax.swing.JTextField txtijabatan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtusia;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables

    private void load_table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID PEGAWAI");
        model.addColumn("ID DIVISI");
        model.addColumn("ID JABATAN");
        model.addColumn("NAMA");
        model.addColumn("GOLONGAN");
        model.addColumn("ALAMAT");
        model.addColumn("USIA");
        
        
        //menampilkan data database ke dalam tabel
        try{
            String sql = "select *from pegawai";
            java.sql.Connection conn= config.configDB();
            
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
               model.addRow(new 
                Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
            }
            JTablePegawai.setModel(model);
        }catch (SQLException e){
            
        }
    }
    
     private void searchData(String keyID){
        try{
            Object [] listkolom = {"ID PEGAWAI", "ID DIVISI", "ID JABTAN",  "NAMA PEGAWAI", "GOLONGAN", "ALAMAT", "USIA"};
            DefaultTableModel dtm = new DefaultTableModel(null, listkolom);
             JTablePegawai.setModel(dtm);
             Connection conn = (Connection)config.configDB();
             dtm.getDataVector().removeAllElements();
             ResultSet resu = conn.createStatement().executeQuery("SELECT * FROM pegawai WHERE id_pegawai LIKE '"+keyID+"%'");
             while(resu.next()){
                 Object[] data = {
                     resu.getString("id_pegawai"),
                     resu.getString("id_divisi"),
                     resu.getString("id_jabatan"),
                     resu.getString("nama"),
                     resu.getString("golongan"),
                     resu.getString("alamat"),
                     resu.getString("usia")
                 };
                 dtm.addRow(data);
             }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void kosong() {
        txtidpegawai.setText(null);
        txtiddivisi.setText(null);
        txtijabatan.setText(null);
        txtnama.setText(null);
        txtalamat.setText(null);
        txtusia.setText(null);
        
    }
}
