import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import simpeg_abdiel.Db;
import simpeg_abdiel.config;

public class FormDivisi extends javax.swing.JFrame {
    
    public FormDivisi() {
        initComponents();
        load_table();
        kosong();
      
    }
    
   
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtiddivisi = new javax.swing.JTextField();
        txtnamadivisi = new javax.swing.JTextField();
        txthonordivisi = new javax.swing.JTextField();
        tambahbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        hapusbtn = new javax.swing.JButton();
        keluarbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableDivisi = new javax.swing.JTable();
        iddivisi = new javax.swing.JLabel();
        namadivisi = new javax.swing.JLabel();
        honordivisi = new javax.swing.JLabel();
        searchbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtiddivisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtiddivisiActionPerformed(evt);
            }
        });
        txtiddivisi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtiddivisiKeyReleased(evt);
            }
        });

        txtnamadivisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamadivisiActionPerformed(evt);
            }
        });

        txthonordivisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthonordivisiActionPerformed(evt);
            }
        });

        tambahbtn.setText("TAMBAH");
        tambahbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahbtnActionPerformed(evt);
            }
        });

        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        hapusbtn.setText("HAPUS");
        hapusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbtnActionPerformed(evt);
            }
        });

        keluarbtn.setText("KELUAR");
        keluarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarbtnActionPerformed(evt);
            }
        });

        JTableDivisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTableDivisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableDivisiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableDivisi);

        iddivisi.setText("ID DIVISI");

        namadivisi.setText("NAMA DIVISI");

        honordivisi.setText("HONOR DIVISI");

        searchbtn.setText("SEARCH");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        clearbtn.setText("CLEAR");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iddivisi)
                            .addComponent(namadivisi)
                            .addComponent(honordivisi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtiddivisi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                            .addComponent(txtnamadivisi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txthonordivisi))
                        .addGap(18, 18, 18)
                        .addComponent(searchbtn)
                        .addGap(18, 18, 18)
                        .addComponent(clearbtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tambahbtn)
                        .addGap(18, 18, 18)
                        .addComponent(updatebtn)
                        .addGap(18, 18, 18)
                        .addComponent(hapusbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(keluarbtn)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtiddivisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iddivisi)
                    .addComponent(searchbtn)
                    .addComponent(clearbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamadivisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namadivisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthonordivisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(honordivisi))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keluarbtn)
                    .addComponent(tambahbtn)
                    .addComponent(updatebtn)
                    .addComponent(hapusbtn))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtiddivisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtiddivisiActionPerformed
        // TODO add your handling code here:
        txtnamadivisi.requestFocus();
        searchbtn.doClick();
          
    }//GEN-LAST:event_txtiddivisiActionPerformed

    private void txtnamadivisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamadivisiActionPerformed
        // TODO add your handling code here:
       txthonordivisi.requestFocus();
    }//GEN-LAST:event_txtnamadivisiActionPerformed

    private void txthonordivisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthonordivisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthonordivisiActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        try {
        String sql ="UPDATE divisi SET id_divisi = '"+txtiddivisi.getText()+"', "+ "nama_divisi = '"+txtnamadivisi.getText()+"', "+ "honor_divisi = '"+txthonordivisi.getText()+"' WHERE id_divisi = '"+txtiddivisi.getText()+"'";
        java.sql.Connection conn=(Connection)config.configDB();
        java.sql.PreparedStatement pst=conn.prepareStatement(sql);
        pst.execute();
        JOptionPane.showMessageDialog(null, "data berhasil diedit");
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
            load_table();
            kosong();
 
    }//GEN-LAST:event_updatebtnActionPerformed

    private void hapusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbtnActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="delete from divisi where id_divisi='"+txtiddivisi.getText()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
             pst.execute();
            JOptionPane.showMessageDialog(this, "berhasil dihapus");
            } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            }
                load_table();
                kosong();

    }//GEN-LAST:event_hapusbtnActionPerformed

    private void keluarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarbtnActionPerformed
        // TODO add your handling code here:
        new menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_keluarbtnActionPerformed

    private void tambahbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahbtnActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO divisi VALUES ('"+txtiddivisi.getText()+"',"+ "'"+txtnamadivisi.getText()+"','"+txthonordivisi.getText()+"')";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
            } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            }
                load_table();
                kosong();

    }//GEN-LAST:event_tambahbtnActionPerformed

    private void txtiddivisiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtiddivisiKeyReleased
        
          String key = txtiddivisi.getText();
        System.out.println(key);
        
        if (key !=""){
            searchData(key);
        }
        else
        {
            load_table();
        }
        
    }//GEN-LAST:event_txtiddivisiKeyReleased

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        try{
            ResultSet rs =  Db.getData ("SELECT * FROM divisi WHERE id_divisi='"+txtiddivisi.getText()+"'");

            if (rs.next()){
                txtiddivisi.setText(rs.getString("id_divisi"));
                txtnamadivisi.setText(rs.getString("nama_divisi"));
                txthonordivisi.setText(rs.getString("honor_divisi"));
            }
            else{
                JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
            }

        }
        catch (Exception e){
            e.printStackTrace();

        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_clearbtnActionPerformed

    private void JTableDivisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableDivisiMouseClicked
        // TODO add your handling code here:
        int baris = JTableDivisi.rowAtPoint(evt.getPoint());
        String id_divisi =JTableDivisi.getValueAt(baris, 0).toString();
        txtiddivisi.setText(id_divisi);      
        String nama_divisi =JTableDivisi.getValueAt(baris, 1).toString();
        txtnamadivisi.setText(nama_divisi);
        String honor_divisi =JTableDivisi.getValueAt(baris, 2).toString();
        txthonordivisi.setText(honor_divisi);
    }//GEN-LAST:event_JTableDivisiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDivisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDivisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDivisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDivisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormDivisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableDivisi;
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton hapusbtn;
    private javax.swing.JLabel honordivisi;
    private javax.swing.JLabel iddivisi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluarbtn;
    private javax.swing.JLabel namadivisi;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton tambahbtn;
    private javax.swing.JTextField txthonordivisi;
    private javax.swing.JTextField txtiddivisi;
    private javax.swing.JTextField txtnamadivisi;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables

    private void load_table() {
        
        //membuat tampilan model table
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID DIVISI");
        model.addColumn("NAMA DIVISI");
        model.addColumn("HONOR DIVISI");
        
        //menampilkan data database ke dalam tabel
        try{
            String sql = "select *from divisi";
            java.sql.Connection conn= config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
               model.addRow(new 
                Object[]{res.getString(1),res.getString(2),res.getString(3)});
            }
            JTableDivisi.setModel(model);
        }catch (SQLException e){
            
        }
    }
    
    private void searchData(String keyID){
        try{
            Object [] listkolom = {"ID", "NAMA DIVISI", "HONOR DIVISI"};
            DefaultTableModel dtm = new DefaultTableModel(null, listkolom);
             JTableDivisi.setModel(dtm);
             Connection conn = (Connection)config.configDB();
             dtm.getDataVector().removeAllElements();
             ResultSet resu = conn.createStatement().executeQuery("SELECT * FROM divisi WHERE id_divisi LIKE '"+keyID+"%'");
             while(resu.next()){
                 Object[] data = {
                     resu.getString("id_divisi"),
                     resu.getString("nama_divisi"),
                     resu.getString("honor_divisi")
                     
                 };
                 dtm.addRow(data);
             }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void kosong() {
        
        txtiddivisi.setText(null);
        txtnamadivisi.setText(null);
        txthonordivisi.setText(null); 
    }
}
