import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import simpeg_abdiel.config;
import simpeg_abdiel.Db;

public class FormJabatan extends javax.swing.JFrame {

    public FormJabatan() {
        initComponents();
        load_table();
        kosong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iddivisi = new javax.swing.JLabel();
        iddivisi1 = new javax.swing.JLabel();
        txtidjabatan = new javax.swing.JTextField();
        txtjabatan = new javax.swing.JTextField();
        tambahbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableJabatan = new javax.swing.JTable();
        iddivisi3 = new javax.swing.JLabel();
        txttunjanganjabatan = new javax.swing.JTextField();
        txtperjdinas = new javax.swing.JTextField();
        iddivisi6 = new javax.swing.JLabel();
        searchbtn = new javax.swing.JButton();
        keluar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iddivisi.setText("ID JABATAN");

        iddivisi1.setText("JABATAN");

        txtidjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidjabatanActionPerformed(evt);
            }
        });
        txtidjabatan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidjabatanKeyReleased(evt);
            }
        });

        txtjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjabatanActionPerformed(evt);
            }
        });

        tambahbtn.setText("TAMBAH");
        tambahbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahbtnActionPerformed(evt);
            }
        });

        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        JTableJabatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTableJabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableJabatanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableJabatan);

        iddivisi3.setText("TUNJANGAN JABATAN");

        txttunjanganjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttunjanganjabatanActionPerformed(evt);
            }
        });

        txtperjdinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtperjdinasActionPerformed(evt);
            }
        });

        iddivisi6.setText("PERJANJIAN DINAS");

        searchbtn.setText("SEARCH");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        keluar1.setText("CLEAR");
        keluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambahbtn)
                        .addGap(18, 18, 18)
                        .addComponent(updatebtn)
                        .addGap(18, 18, 18)
                        .addComponent(btnhapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(keluar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iddivisi1)
                            .addComponent(iddivisi3)
                            .addComponent(iddivisi)
                            .addComponent(iddivisi6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtidjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchbtn)
                                .addGap(18, 18, 18)
                                .addComponent(keluar1))
                            .addComponent(txttunjanganjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtperjdinas, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iddivisi)
                    .addComponent(searchbtn)
                    .addComponent(keluar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iddivisi1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttunjanganjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iddivisi3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtperjdinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iddivisi6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhapus)
                    .addComponent(updatebtn)
                    .addComponent(tambahbtn)
                    .addComponent(keluar))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidjabatanActionPerformed
        // TODO add your handling code here:
        txtjabatan.requestFocus();
        searchbtn.doClick();
    }//GEN-LAST:event_txtidjabatanActionPerformed

    private void txtjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjabatanActionPerformed
        // TODO add your handling code here:
        txttunjanganjabatan.requestFocus();
    }//GEN-LAST:event_txtjabatanActionPerformed

    private void tambahbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahbtnActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO jabatan VALUES ('"+txtidjabatan.getText()+"',"+ "'"+txtjabatan.getText()+"', '"+txttunjanganjabatan.getText()+"', '"+txtperjdinas.getText()+"')";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_tambahbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="UPDATE jabatan SET id_jabatan = '"+txtidjabatan.getText()+"', "+ "jabatan = '"+txtjabatan.getText()+"',  "+ "tunj_jabatan = '"+txttunjanganjabatan.getText()+"', "+ "perj_dinas = '"+txtperjdinas.getText()+"' WHERE id_jabatan = '"+txtidjabatan.getText()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        load_table();
        kosong();

    }//GEN-LAST:event_updatebtnActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="delete from jabatan where id_jabatan='"+txtidjabatan.getText()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
             pst.execute();
            JOptionPane.showMessageDialog(this, "berhasil di hapus");
            } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            }
                load_table();
                kosong();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        new menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void txttunjanganjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttunjanganjabatanActionPerformed
        // TODO add your handling code here:
        txtperjdinas.requestFocus();
    }//GEN-LAST:event_txttunjanganjabatanActionPerformed

    private void txtperjdinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtperjdinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtperjdinasActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        try{
            ResultSet rs =  Db.getData ("SELECT * FROM jabatan WHERE id_jabatan='"+txtidjabatan.getText()+"'");

            if (rs.next()){
                txtjabatan.setText(rs.getString("jabatan"));
                txttunjanganjabatan.setText(rs.getString("tunj_jabatan"));
                txtperjdinas.setText(rs.getString("perj_dinas"));
            }
            else{
                 JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
            }
           
        }
        catch (Exception e){
            e.printStackTrace();
            
        }

    }//GEN-LAST:event_searchbtnActionPerformed

    private void txtidjabatanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidjabatanKeyReleased
        // TODO add your handling code here:
        String key = txtidjabatan.getText();
        System.out.println(key);
        
        if (key !=""){
            searchData(key);
        }
        else
        {
            load_table();
        }
    }//GEN-LAST:event_txtidjabatanKeyReleased

    private void keluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluar1ActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_keluar1ActionPerformed

    private void JTableJabatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableJabatanMouseClicked
        // TODO add your handling code here:
         int baris = JTableJabatan.rowAtPoint(evt.getPoint());
        String id_jabatan =JTableJabatan.getValueAt(baris, 0).toString();
        txtidjabatan.setText(id_jabatan);      
        String jabatan =JTableJabatan.getValueAt(baris, 1).toString();
        txtjabatan.setText(jabatan);
        String tunj_jabatan =JTableJabatan.getValueAt(baris, 2).toString();
        txttunjanganjabatan.setText(tunj_jabatan);
        String perj_jabatan =JTableJabatan.getValueAt(baris, 3).toString();
        txtperjdinas.setText(perj_jabatan);
    }//GEN-LAST:event_JTableJabatanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormJabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormJabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormJabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormJabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormJabatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableJabatan;
    private javax.swing.JButton btnhapus;
    private javax.swing.JLabel iddivisi;
    private javax.swing.JLabel iddivisi1;
    private javax.swing.JLabel iddivisi3;
    private javax.swing.JLabel iddivisi6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton keluar1;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton tambahbtn;
    private javax.swing.JTextField txtidjabatan;
    private javax.swing.JTextField txtjabatan;
    private javax.swing.JTextField txtperjdinas;
    private javax.swing.JTextField txttunjanganjabatan;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables

    private void load_table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID JABATAN");
        model.addColumn("JABATAN");
        model.addColumn("TUNJANGAN JABATAN");
        model.addColumn("PERJALANAN DINAS");
        
        //menampilkan data database ke dalam tabel
        try{
            String sql = "select *from jabatan";
            java.sql.Connection conn= config.configDB();
            
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
               model.addRow(new 
                Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
            }
            JTableJabatan.setModel(model);
        }catch (SQLException e){
            
        }
    }
    
    private void searchData(String keyID){
        try{
            Object [] listkolom = {"ID", "JABATAN", "TUNJANGAN", "PERJALANAN"};
            DefaultTableModel dtm = new DefaultTableModel(null, listkolom);
             JTableJabatan.setModel(dtm);
             Connection conn = (Connection)config.configDB();
             dtm.getDataVector().removeAllElements();
             ResultSet resu = conn.createStatement().executeQuery("SELECT * FROM jabatan WHERE id_jabatan LIKE '"+keyID+"%'");
             while(resu.next()){
                 Object[] data = {
                     resu.getString("id_jabatan"),
                     resu.getString("jabatan"),
                     resu.getString("tunj_jabatan"),
                     resu.getString("perj_dinas")
                     
                 };
                 dtm.addRow(data);
             }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }


    private void kosong() {
        txtidjabatan.setText(null);
        txtjabatan.setText(null);
        txttunjanganjabatan.setText(null);
        txtperjdinas.setText(null);
        
    }
}
